### ISSUE TITLE
[BUG] 将资源包删除不会下载复制资源包至资源包文件夹

### ISSUE THREAD

**Issue by zkitefly** [ThinkingStudios/I18nUpdateMod-NLTS-old#19]
**描述错误**
简明扼要地描述该错误是什么。

**如何重现**
将资源包文件夹删除，然后启动游戏，并不会下载复制资源包至资源包文件夹

**屏幕截图**
![image](https://user-images.githubusercontent.com/64117916/212232174-4f4f5702-f354-4959-93ee-e9e920033f74.png)

**设备信息：**
 - 操作系统：
 - 游戏版本：1.19.3
 - 模组加载器：Forge
 - 模组版本：i18nUpdateMod-NLTS-Forge-1.0.3beta1-hotfix1-1.19.3.jar
                      cloth-config-9.0.94-forge.jar

**额外信息**
加速链接应该是没啥问题的
![image](https://user-images.githubusercontent.com/64117916/212233015-6d59ef93-4194-473e-b8ca-45fed8f362dd.png)
没有任何的字符，空格
![fad4ea9cd5360f31c5f8fcd25c0adcfe](https://user-images.githubusercontent.com/64117916/212233118-a04286cc-06fe-43c5-b841-7c5a43158869.png)
TranslationPackConvert 资源没有问题
![14d1f9c4c717423e5bc511f9475da842](https://user-images.githubusercontent.com/64117916/212233156-b3f22a62-5a6f-43a0-a253-aea4494f62cb.png)

**Comment by TexBlock** [comment]
奇怪，我这好像没有这个问题

**Comment by TexBlock** [comment]
[latest.log](https://github.com/TexTrueStudio/I18nUpdateMod-NLTS/files/10408265/latest.log)

![image](https://user-images.githubusercontent.com/65154269/212240273-59fdf446-f2f6-421e-abda-77ee53f4b75c.png)

emmm，好像情况不一样？

**Comment by zkitefly** [comment]
已修复，原因是 MD5 校验值不是大写导致，目前那边已修复
