### ISSUE TITLE
[BUG] 1.19.3 Fabric 崩溃

### ISSUE THREAD

**Issue by AkarinLiu** [ThinkingStudios/I18nUpdateMod-NLTS-old#5]
[minecraft-exported-logs-2022-12-26T13-30-42.log](https://github.com/TexTrueStudio/I18nUpdateMod-NLTS/files/10301712/minecraft-exported-logs-2022-12-26T13-30-42.log)

**Comment by TexBlock** [comment]
请提供crash report
文件夹路径为`.minecraft\crash-reports`

**Comment by TexBlock** [comment]
已单独发布1.19.3版本
