### ISSUE TITLE
建议使用 github + 加速源 作为镜像源分发下载资源包

### ISSUE THREAD

**Issue by zkitefly** [ThinkingStudios/I18nUpdateMod-NLTS-old#8]
https://github.com/CFPAOrg/I18nUpdateMod2/issues/57

因为服务器压力过大，我的建议是使用 github + 加速源 来分发下载资源包

我这边已经准备好了 https://github.com/zkitefly/I18nUpdateMod-resources#readme

将所有链接的 http://downloader1.meitangdehulu.com:22943/ 替换成 https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackMirror/main/files/

*这里改了下地址*

不知可否？

**Comment by TexBlock** [comment]
你的仓库内的资源包是自动抓取的还是手动

**Comment by zkitefly** [comment]
> 你的仓库内的资源包是自动抓取的还是手动

自动，通过 github-action 自动从 http://downloader1.meitangdehulu.com:22943/ 获取

也不用太担心同步问题，他会每一小时检查一次

**Comment by TexBlock** [comment]
ok，我将会在下个版本（1.0.3，arch1.1.3，legacy0.1.1）加入config，到时候默认是这个镜像。

但是我仍然担心镜像的稳定性，不知道带宽是否能承受住？或者可以迁移到其他的代码托管平台（除了gitee）？

**Comment by zkitefly** [comment]
https://github.com/zkitefly/TranslationPackMirror#readme

此处还有很多下载地址，或许可以尝试随机使用某个地址以分摊压力？

**Comment by zkitefly** [comment]
![image](https://user-images.githubusercontent.com/64117916/211291371-c23cc78f-92d5-4f46-8b8d-efc976108c59.png)

[GitHub Proxy](https://ghproxy.com/)镜像源

**Comment by TexBlock** [comment]
好吧，看来只有这样了，会在下个版本作为默认下载源。

**Comment by TexBlock** [comment]
> 此处还有很多下载地址，或许可以尝试随机使用某个地址以分摊压力？

目前以我的技术有点困难🥲（

**Comment by zkitefly** [comment]
我技术也很糟糕（
弄这个自动获取弄了一天一夜（

**Comment by zkitefly** [comment]
![image](https://user-images.githubusercontent.com/64117916/211353047-5f7d19df-b540-4b4e-b6f0-783893d11651.png)
玩了
为啥github-action获取不到资源的？
总是超时的（
**在解决这个问题前先暂时不添加至默认镜像源（**

**Comment by zkitefly** [comment]
> ![image](https://user-images.githubusercontent.com/64117916/211353047-5f7d19df-b540-4b4e-b6f0-783893d11651.png) 玩了 为啥github-action获取不到资源的？ 总是超时的（ **在解决这个问题前先暂时不添加至默认镜像源（**

解决了
暴力刷新 github-action 的 dns 缓存（

**Comment by TexBlock** [comment]
![image](https://user-images.githubusercontent.com/65154269/211422498-d70a9d5e-90d8-417b-9b4d-4d2fd461c61b.png)

你好像把files文件夹删了，导致action cd 不到这个文件夹

**Comment by zkitefly** [comment]
现在可以了

**Comment by zkitefly** [comment]
我要不要我发个 PR ？

**Comment by TexBlock** [comment]
> 我要不要我发个 PR ？

可以，我最近一直在上网课，时间不多。

**Comment by zkitefly** [comment]
我有个想法，能在换一次地址吗，我来开PR

**Comment by TexBlock** [comment]
> 我有个想法，能在换一次地址吗，我来开PR

什么想法？

**Comment by zkitefly** [comment]
想换地址（我在想那个最合适）

**Comment by zkitefly** [comment]
例如这样
![image](https://user-images.githubusercontent.com/64117916/211499996-882d31d5-268f-4c0d-92c7-29ec17b37ed3.png)

**Comment by TexBlock** [comment]
我一会写个config吧，这么改太麻烦了

**Comment by zkitefly** [comment]
ok
`https://cdn.staticaly.com/gh/zkitefly/TranslationPackMirror/main/files/`
我想这个地址最合适

**Comment by zkitefly** [comment]
> ok `https://cdn.staticaly.com/gh/zkitefly/TranslationPackMirror/main/files/` 我想这个地址最合适

先待会弄一下，我再观察一会

**Comment by zkitefly** [comment]
> > ok `https://cdn.staticaly.com/gh/zkitefly/TranslationPackMirror/main/files/` 我想这个地址最合适
> 
> 先待会弄一下，我再观察一会

算了，就原来那个吧，这个有点不稳定
抱歉绕了这么多弯（

**Comment by zkitefly** [comment]
我这找到了个好玩的功能，
![image](https://user-images.githubusercontent.com/64117916/211609959-bc4da1f3-0859-47fd-a70a-7bffb1925657.png)
我之后尝试通过 github-action 来自动将资源包的 `pack_format` key 的 value 修改成合适的值，使其能够正常被游戏加载
你看怎么样QWQ

**Comment by zkitefly** [comment]
> 我这找到了个好玩的功能， ![image](https://user-images.githubusercontent.com/64117916/211609959-bc4da1f3-0859-47fd-a70a-7bffb1925657.png) 我之后尝试通过 github-action 来自动将资源包的 `pack_format` key 的 value 修改成合适的值，使其能够正常被游戏加载 你看怎么样QWQ

仓库已经创建，明天开始写：https://github.com/zkitefly/TranslationPackConvert

**Comment by zkitefly** [comment]
> > 我这找到了个好玩的功能， ![image](https://user-images.githubusercontent.com/64117916/211609959-bc4da1f3-0859-47fd-a70a-7bffb1925657.png) 我之后尝试通过 github-action 来自动将资源包的 `pack_format` key 的 value 修改成合适的值，使其能够正常被游戏加载 你看怎么样QWQ
> 
> 仓库已经创建，明天开始写：https://github.com/zkitefly/TranslationPackConvert

![image](https://user-images.githubusercontent.com/64117916/211707208-db5e11e7-658f-4223-860a-fffc9a3e0a27.png)

我已经做了差不多了，但是出了个问题，不知道怎么解决（

解决是解决了，但还有些其他的问题，继续抓小虫子（

**Comment by TexBlock** [comment]
为什么不从资源包打包入手？这样不是更方便吗

**Comment by zkitefly** [comment]
> 为什么不从资源包打包入手？这样不是更方便吗

打包那的 action 看晕了（

还不如直接解压，修改，然后再打包

**Comment by zkitefly** [comment]
https://github.com/zkitefly/TranslationPackConvert 已经可用啦，我现在提交 PR 
（对着日志弄了两天两夜终于好了，痛苦）

**Comment by zkitefly** [comment]
![image](https://user-images.githubusercontent.com/64117916/211892253-b17d21e0-07c1-4a76-8522-15c82f5fa69e.png)
![image](https://user-images.githubusercontent.com/64117916/211892330-8d6b6702-202b-42eb-b65b-b400bd5c1712.png)

**Comment by zkitefly** [comment]
测试了一下，应该是没什么问题了：
![](https://api.onedrive.com/v1.0/shares/s!AiSrzi-vYVoBhB8DB6RdiwO8PFp9/root/content)

**Comment by TexBlock** [comment]
> 测试了一下，应该是没什么问题了： ![](https://camo.githubusercontent.com/e4c03ede2d287bcdfef3ebae3f5717896843862fa57ae74744d2a41d84561d94/68747470733a2f2f6170692e6f6e6564726976652e636f6d2f76312e302f7368617265732f7321416953727a692d7659566f42684238444236526469774f38504670392f726f6f742f636f6e74656e74)

那我一会发布一下对那三个版本的修复版本

**Comment by zkitefly** [comment]
ok
我改一下mcmod的内容

**Comment by TexBlock** [comment]
> ok 我改一下mcmod的内容

资料那边我还是自己改吧（

**Comment by zkitefly** [comment]
> > ok 我改一下mcmod的内容
> 
> 资料那边我还是自己改吧（

好吧

**Comment by zkitefly** [comment]
等一下，我问下1.12.2换了吗？

**Comment by TexBlock** [comment]
> 等一下，我问下1.12.2换了吗？

1.12.2还没做，正在做（

**Comment by zkitefly** [comment]
ok

**Comment by zkitefly** [comment]
新消息，gitcode同步已经完成，gitcode的各项指标都非常棒：

![](https://api.onedrive.com/v1.0/shares/s!AiSrzi-vYVoBhB4PrXvES6IJLgNL/root/content)

![](https://api.onedrive.com/v1.0/shares/s!AiSrzi-vYVoBhCBXhWF2omNpPJP-/root/content)
```
zkitefly@zkitefly:~$ wget https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackConvert/main/files/Minecraft-Mod-Language-Modpack-1-16T1-17.zip # ghproxy.com下载
--2023-01-14 16:09:33--  https://ghproxy.com/https://raw.githubusercontent.com/zkitefly/TranslationPackConvert/main/files/Minecraft-Mod-Language-Modpack-1-16T1-17.zip
正在解析主机 ghproxy.com (ghproxy.com)... 140.83.35.89
正在连接 ghproxy.com (ghproxy.com)|140.83.35.89|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：4724456 (4.5M) [application/zip]
正在保存至: “Minecraft-Mod-Language-Modpack-1-16T1-17.zip”

Minecraft-Mod-Language-Modp 100%[========================================>]   4.50M  5.49MB/s  用时 0.8s    

2023-01-14 16:09:36 (5.49 MB/s) - 已保存 “Minecraft-Mod-Language-Modpack-1-16T1-17.zip” [4724456/4724456])

已发出 HTTP 请求，正在等待回应... 301 Moved Permanently
位置：https://gitcode.net/chearlai/translationpackmirror/-/raw/main/files/Minecraft-Mod-Language-Modpack.zip [跟随至新的 URL]
--2023-01-14 17:42:47--  https://gitcode.net/chearlai/translationpackmirror/-/raw/main/files/Minecraft-Mod-Language-Modpack.zip
再次使用存在的到 gitcode.net:443 的连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：6878349 (6.6M) [application/zip]
正在保存至: “Minecraft-Mod-Language-Modpack.zip.3”

Minecraft-Mod-Lan 100%[============>]   6.56M  8.13MB/s  用时 0.8s    

2023-01-14 17:42:48 (8.13 MB/s) - 已保存 “Minecraft-Mod-Language-Modpack.zip.3” [6878349/6878349])


```
